package lab.helpdesk.ai.job;

public enum AiJobFailureCode {
    PROVIDER_REFUSED,
    PROVIDER_RATE_LIMITED,
    PROVIDER_OUTCOME_UNKNOWN,
    OUTPUT_INVALID,
    OUTPUT_REQUIRED_FIELD_MISSING,
    OUTPUT_REPAIR_LIMIT_EXHAUSTED,
    GENERATION_LIMIT_EXHAUSTED,
    JOB_PROCESSING_DEADLINE_EXCEEDED,
    ADAPTER_CONFIGURATION_ERROR
}
