CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT tickets_title_not_blank
        CHECK (btrim(title) <> ''),
    CONSTRAINT tickets_status_allowed
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);
