CREATE TABLE ticket_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets (id),
    body TEXT NOT NULL,
    author_username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ticket_messages_body_not_blank
        CHECK (btrim(body) <> ''),
    CONSTRAINT ticket_messages_author_not_blank
        CHECK (btrim(author_username) <> '')
);

CREATE INDEX ticket_messages_ticket_id_idx ON ticket_messages (ticket_id);

CREATE TABLE ai_suggestion_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_message_id BIGINT NOT NULL REFERENCES ticket_messages (id),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_suggestion_jobs_input_message_unique
        UNIQUE (input_message_id),
    CONSTRAINT ai_suggestion_jobs_pending_only
        CHECK (status = 'PENDING')
);
